owner: synaptic-cl
repo: BOUFIN-uptime 

sites:
  - name: Synaptic.cl
    url: https://synaptic.cl/

  - name: Boufin.com
    url: https://boufin.com/

  - name: Boufin Docs
    url: https://doc.boufin.com/

  - name: Widget
    url: https://widget.boufin.com/

  - name: Widget DEMO
    url: https://demo-widget.boufin.com/

  - name: Widget SandBox 
    url: https://widget-sandbox.boufin.com/

  - name: Widget SandBox DEMO
    url: https://demo-widget-sandbox.boufin.com/


asignees:
  - tebancl
  - hvillarroel

status-website:
  cname: status.boufin.com
  logoUrl: https://storage.googleapis.com/sy-public-assets/boufin-logo.svg
  favicon: https://storage.googleapis.com/sy-public-assets/boufin-favicon.ico
  theme: light
  name: ""
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
